In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## 1.2 讀取 .csv

In [2]:
data = pd.read_csv('housing.csv')    #讀CSV的方式,若非同個資料夾要注意路徑

In [3]:
data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [4]:
data.dropna(inplace=True)    #直接更新data,若沒有inplace不會真的drop

In [5]:
data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20433 rows x 10 columns]

In [6]:
x = np.array(data)[:, :8]    #data 取0~8變成x ":"從0開始全取,array轉矩陣取前面8欄
x

array([[-122.23, 37.88, 41.0, ..., 322.0, 126.0, 8.3252],
       [-122.22, 37.86, 21.0, ..., 2401.0, 1138.0, 8.3014],
       [-122.24, 37.85, 52.0, ..., 496.0, 177.0, 7.2574],
       ...,
       [-121.22, 39.43, 17.0, ..., 1007.0, 433.0, 1.7],
       [-121.32, 39.43, 18.0, ..., 741.0, 349.0, 1.8672],
       [-121.24, 39.37, 16.0, ..., 1387.0, 530.0, 2.3886]], dtype=object)

In [7]:
x.shape

(20433, 8)

In [8]:
y = np.array(data)[:, 8]    #只有一欄變成向量,一個維度
y.shape

(20433,)

In [9]:
y

array([452600.0, 358500.0, 352100.0, ..., 92300.0, 84700.0, 89400.0],
      dtype=object)

In [10]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(x,y)

LinearRegression()

In [11]:
lin_reg.intercept_, lin_reg.coef_

(-3585395.7478924464,
 array([-4.27301205e+04, -4.25097369e+04,  1.15790031e+03, -8.24972507e+00,
         1.13820707e+02, -3.83855780e+01,  4.77013513e+01,  4.02975217e+04]))

# 第0筆房價預測結果 Predict (linear regression)

In [12]:
x[0].shape

(8,)

In [13]:
x_new = x[0].reshape(1,8)
x_new.shape

(1, 8)

In [14]:
lin_reg.predict(x_new)

array([411270.20746023])

# 第0筆房價預測結果 Predict (SGD)

In [15]:
from sklearn.preprocessing import StandardScaler    

scal = StandardScaler()
x_scal = scal.fit_transform(x)

In [16]:
x_scal

array([[-1.32731375,  1.05171726,  0.98216331, ..., -0.97331952,
        -0.97683327,  2.34516291],
       [-1.32232256,  1.04235526, -0.60621017, ...,  0.86133924,
         1.67037262,  2.33263161],
       [-1.33230494,  1.03767426,  1.85576873, ..., -0.81976943,
        -0.84342665,  1.78293943],
       ...,
       [-0.82320322,  1.77727236, -0.92388486, ..., -0.36882637,
        -0.17377773, -1.14317103],
       [-0.87311515,  1.77727236, -0.84446619, ..., -0.60356386,
        -0.39350628, -1.05513604],
       [-0.83318561,  1.74918635, -1.00330353, ..., -0.03348711,
         0.07995643, -0.78060586]])

In [17]:
from sklearn.linear_model import SGDRegressor

sgd_reg = SGDRegressor(max_iter=1000, tol=1e-3, penalty=None, eta0=.1)    #超參數調整, tolerance= ε,eta0=0.1=學習速率的初始值
sgd_reg.fit(x_scal,y.ravel())

SGDRegressor(eta0=0.1, penalty=None)

In [18]:
sgd_reg.intercept_, sgd_reg.coef_

(array([201540.09051289]),
 array([-90621.69916018, -88039.73043043,  13364.29092492, -14063.89672839,
         49436.10989402, -54189.91417049,  17372.82412925,  74950.14121092]))

In [19]:
x_new = x[0].reshape(1,8)
x_new.shape

(1, 8)

In [20]:
x_new_scal = scal.transform(x_new) 

In [21]:
sgd_reg.predict(x_new_scal)

array([417236.20300689])