學號：0111109069 姓名：李佳毓
作業題目：regression code + w4 的2個Codes
繳交期限：2022/10/8 9:30

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv('housing.csv')
data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [3]:
data.dropna(inplace=True) 
data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20433 rows x 10 columns]

In [4]:
x = np.array(data)[:, :8]    #data 取0~8變成x ":"從0開始全取,array轉矩陣取前面8欄
x

array([[-122.23, 37.88, 41.0, ..., 322.0, 126.0, 8.3252],
       [-122.22, 37.86, 21.0, ..., 2401.0, 1138.0, 8.3014],
       [-122.24, 37.85, 52.0, ..., 496.0, 177.0, 7.2574],
       ...,
       [-121.22, 39.43, 17.0, ..., 1007.0, 433.0, 1.7],
       [-121.32, 39.43, 18.0, ..., 741.0, 349.0, 1.8672],
       [-121.24, 39.37, 16.0, ..., 1387.0, 530.0, 2.3886]], dtype=object)

In [5]:
x.shape

(20433, 8)

In [6]:
y = np.array(data)[:, 8]    #只有一欄變成向量,一個維度
y.shape

(20433,)

In [7]:
y

array([452600.0, 358500.0, 352100.0, ..., 92300.0, 84700.0, 89400.0],
      dtype=object)

# Spilt 訓練集/測試集

In [8]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

# Ridge Regression

In [9]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler

## 使用Ridge() : Closed-form

In [10]:
m= aplha = 2.5
from sklearn.linear_model import Ridge
ridge_reg = Pipeline([
    ('poly', PolynomialFeatures(degree=4, include_bias=False)),
    ('scal', StandardScaler()),
    ('ridge', Ridge(alpha=m/2, random_state=1))
])
ridge_reg.fit(x_train, y_train)

Pipeline(steps=[('poly', PolynomialFeatures(degree=4, include_bias=False)),
                ('scal', StandardScaler()),
                ('ridge', Ridge(alpha=1.25, random_state=1))])

In [11]:
ridge_reg.score(x_train, y_train), ridge_reg.score(x_test, y_test)

(0.7409129834388539, 0.7404190288381505)

In [12]:
ridge_reg.predict(x_test[:1])

array([442741.37864025])

## 使用SGDRegressor() : 梯度下降

In [13]:
from sklearn.linear_model import SGDRegressor
ridge_sgd = Pipeline([
    ('poly', PolynomialFeatures(degree=3, include_bias=False)),
    ('scal', StandardScaler()),
    ('ridge', SGDRegressor(penalty='l2', alpha=9,  random_state=1))
])
ridge_sgd.fit(x_train, y_train.ravel())

Pipeline(steps=[('poly', PolynomialFeatures(degree=3, include_bias=False)),
                ('scal', StandardScaler()),
                ('ridge', SGDRegressor(alpha=9, random_state=1))])

In [14]:
ridge_sgd.score(x_train, y_train), ridge_sgd.score(x_test, y_test)

(0.438601450520982, 0.44747872849984316)

In [15]:
ridge_sgd.predict(x_test[:1])

array([345095.11819062])

# Lesso

# Lesso Regression

In [16]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler

## 使用Lasso()

In [17]:
m = alpha = 3000
from sklearn.linear_model import Lasso
lasso_reg = Pipeline([
    ('poly', PolynomialFeatures(degree=4, include_bias=False)),
    ('scal', StandardScaler()),
    ('lasso', Lasso(alpha=m, random_state=1))
])
lasso_reg.fit(x_train, y_train)

Pipeline(steps=[('poly', PolynomialFeatures(degree=4, include_bias=False)),
                ('scal', StandardScaler()),
                ('lasso', Lasso(alpha=3000, random_state=1))])

In [18]:
lasso_reg.score(x_train, y_train), lasso_reg.score(x_test, y_test)

(0.63118238229998, 0.6367763388470566)

In [19]:
lasso_reg.predict(x_test[:1])

array([402460.56047657])

## 使用SGDRegressor() : 梯度下降

In [20]:
m = alpha = 0.9
from sklearn.linear_model import SGDRegressor
lasso_sgd = Pipeline([
    ('poly', PolynomialFeatures(degree=2, include_bias=False)),
    ('scal', StandardScaler()),
    ('lasso', SGDRegressor(penalty='l1', alpha=m))
])
lasso_sgd.fit(x_train, y_train.ravel())

Pipeline(steps=[('poly', PolynomialFeatures(include_bias=False)),
                ('scal', StandardScaler()),
                ('lasso', SGDRegressor(alpha=0.9, penalty='l1'))])

In [21]:
lasso_sgd.score(x_train, y_train), lasso_sgd.score(x_test, y_test)

(0.6698571126042856, 0.6714944238127472)

In [22]:
lasso_sgd.predict(x_test[:1])

array([394243.98176475])

# Elastic Net

In [23]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler

In [24]:
m = alpha = 0.2725
from sklearn.linear_model import ElasticNet
elastic_reg = Pipeline([
    ('poly', PolynomialFeatures(degree=2, include_bias=False)),
    ('scal', StandardScaler()),
    ('elastic', ElasticNet(alpha=m, l1_ratio=0.5))
])

In [25]:
elastic_reg.fit(x_train, y_train)

Pipeline(steps=[('poly', PolynomialFeatures(include_bias=False)),
                ('scal', StandardScaler()),
                ('elastic', ElasticNet(alpha=0.2725))])

In [26]:
elastic_reg.score(x_train, y_train), elastic_reg.score(x_test, y_test)

(0.638068730054399, 0.642527675496732)

In [27]:
elastic_reg.predict(x_test[:1])

array([395387.49391342])

## 使用SGDRegressor() : 梯度下降

In [28]:
from sklearn.linear_model import SGDRegressor
elastic_sgd = Pipeline([
    ('poly', PolynomialFeatures(degree=2, include_bias=False)),
    ('scal', StandardScaler()),
    ('elastic', SGDRegressor(penalty='l2', l1_ratio=0.5, alpha=m))
])
elastic_sgd.fit(x_train, y_train.ravel())

Pipeline(steps=[('poly', PolynomialFeatures(include_bias=False)),
                ('scal', StandardScaler()),
                ('elastic', SGDRegressor(alpha=0.2725, l1_ratio=0.5))])

In [29]:
elastic_sgd.score(x_train, y_train), elastic_sgd.score(x_test, y_test)

(0.6128168399292583, 0.6181905536250669)

In [30]:
elastic_sgd.predict(x_test[:1])

array([404719.18086512])